name: Deploy website on push from GITHUB to CPANEL 

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  web-deploy:
    name: Deploy to mittal.blog
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Sync Articles
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.MITTAL_BLOG_FTP_SERVER }}
        ftp-username: ${{ secrets.MITTAL_FTP_USERNAME}}
        ftp-password: ${{ secrets.MITTAL_FTP_PASSWORD }}
        server-dir: /public_html/