name: Publish to WordPress

on:
  push:
    paths:
      - "*.html"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Publish to WordPress
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
        run: |
          for file in *.html; do
            content=$(cat $file)
            title=$(basename $file .html)
            curl -X POST "$WP_URL/wp-json/wp/v2/posts" \
            -H "Content-Type: application/json" \
            -u "$WP_USER:$WP_APP_PASSWORD" \
            -d "{\"title\":\"$title\",\"content\":\"$content\",\"status\":\"publish\"}"
          done
